services:
  spark-notebook:
    image: jupyter/pyspark-notebook:spark-3.4.1
    container_name: spark-notebook
    command:
      - start-notebook.py
      - --ServerApp.token=
      - --ServerApp.password=
    ports:
      - "8888:8888"
      - "4040:4040"
    env_file:
      - .env
    environment:
      - SPARK_LOCAL_IP=0.0.0.0
      - PYSPARK_PYTHON=python
      - SPARK_EXTRA_CLASSPATH=/home/jovyan/jars/*
    volumes:
      - ./notebooks:/home/jovyan/work
      - ./jars:/home/jovyan/jars
      - ./evidence:/home/jovyan/evidence
